version: '3.8'
services:
  gateway:
    build: .
    image: task-bot
    container_name: task-bot
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9191:9191"
      - "9192:9192"
    depends_on:
      - db
    environment:
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=task-bot-db
      - DB_HOST=db
    command: ["java", "-jar", "/task-bot.jar"]

  db:
    image: postgres:14-alpine
    container_name: task-bot-db
    shm_size: 128mb
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=task-bot-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root