create table if not exists users
(
    id   bigint not null primary key,
    name varchar(255)
);

create table if not exists goals
(
    id         bigint generated by default as identity primary key,
    owner_id   bigint           not null references users (id) on delete cascade,
    created_on timestamp(6)     not null,
    start      timestamp(6)     not null,
    deadline   timestamp(6)     not null,
    importance double precision not null,
    title      varchar(255)     not null unique,
    status     varchar(20)      not null
);